---

###
# Metronome Service
###

- block:

  - name: Add override directory for metronome.service
    file:
      name: /etc/systemd/system/metronome.service.d
      state: directory

  - name: Add unit-file with custom settings
    template:
      src: metronome.service.j2
      dest: /etc/systemd/system/metronome.service.d/override.conf
    notify: reload systemd and restart metronome

  when: ansible_service_mgr == "systemd"

- block:

  - name: Add defaults-file with settings
    template:
      src: metronome.default.j2
      dest: /etc/default/metronome
    notify: restart metronome

  when: ansible_service_mgr != "systemd"

###
# Local JS
###

- name: Replace local.js file
  template:
    src: local.js.j2
    dest: /usr/share/metronome/html/local.js
  when: metronome_replace_local_js
