---

###
# Metronome Service
###

- block:

  - name: Add override directory for metronome.service
    file:
      name: /etc/systemd/system/metronome.service.d
      state: directory

  - name: Add unit-file with custom settings
    template:
      src: metronome.service.j2
      dest: /etc/systemd/system/metronome.service.d/override.conf
    notify: reload systemd and restart metronome

  when: ansible_service_mgr == "systemd"

- block:

    - name: Add defaults-file with settings
      template:
        src: metronome.default.j2
        dest: /etc/default/metronome
      notify: restart metronome

  when: ansible_service_mgr != "systemd"

###
# Local JS
###

- name: Replace local.js file
  template:
    src: local.js.j2
    dest: /usr/share/metronome/html/local.js
  when: metronome_replace_local_js

###
# Cleanup Cronjob
###

- name: Configure the clean-up cronjob script
  cron:
    name: "metronome: clean-up old data"
    job: "find {{ metronome_stats_directory }}/ -mtime +{{ metronome_cleanup_job_retention }} -delete"
    user: "root"
    weekday: "{{ metronome_cleanup_job_weekday }}"
    hour: "{{ metronome_cleanup_job_hour }}"
    minute: "{{ metronome_cleanup_job_minute }}"
  when: metronome_cleanup_job_enabled
