---
- name: Get the name of the package
  set_fact:
    metronome_pkg_name: "{{ metronome_url_url.split('/')[-1] }}"

- name: Download metronome rpm
  get_url:
    dest: "/var/cache/yum/{{metronome_pkg_name}}"
    url: "{{metronome_url_url}}"
    checksum: "{{metronome_url_checksum}}"
  register: metronome_download

- name: Uninstall old metronome version
  yum:
    name: metronome
    state: absent
  when: metronome_download.changed
  failed_when: False

- name: Install metronome rpm
  yum: name="/var/cache/yum/{{metronome_pkg_name}}" state=present
  when: metronome_download.changed
