---
- name: Get the name of the package
  set_fact:
    metronome_pkg_name: "{{ metronome_url_url.split('/')[-1] }}"

- name: Download metronome rpm
  get_url:
    dest="/var/cache/yum/{{metronome_pkg}}"
    url="{{metronome_url_url}}"
    checksum="{{metronome_url_checksum}}"
  register: metronome_download

- name: Install metronome rpm
  yum: name="/var/cache/apt/{{metronome_pkg}}" state=latest
  when: metronome_downloaded.changed
