---
- name: Download metronome deb
  get_url:
    dest="/tmp/metronome_{{ metronome_version }}_amd64.deb"
    url="https://downloads.powerdns.com/metronome/metronome_{{ metronome_version }}_amd64.deb"
    checksum={{metronome_checksum}}
  register: metronome_downloaded

- name: Install metronome deb
  apt: deb="/tmp/metronome_{{ metronome_version }}_amd64.deb"
  when: metronome_downloaded.changed

- name: replace local.js
  template: src=local.js.j2 dest=/usr/share/metronome/html/local.js

- name: Add unit-file with custom settings
  template: src=metronome.service.j2 dest=/etc/systemd/system/metronome.service
  notify:
   - systemctl daemon-reload (metronome)
   - restart metronome

- name: Enable the metronome service
  service: name=metronome state=started enabled=true
