---
- include: "install.url-{{ansible_os_family}}.yml"
  when: metronome_installation_source == "url"

- include: "install.pkg-{{ansible_os_family}}.yml"
  when: metronome_installation_source == "packages"

- include: metronome-service.yml

- include: local-js.yml
  when: metronome_replace_local_js

- name: Enable the metronome service
  service: name=metronome state=started enabled=true
