---

- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - always

###
# Metronome Repository
###

- include: "repo-{{ ansible_os_family }}.yml"
  when: metronome_install_repo != ""
  tags:
    - install
    - repository

###
# Metronome Setup
###

- name: Install metronome
  package:
    name: metronome
    state: present
  tags:
    - install

- name: Install Metronome debug symbols
  package:
    name: "{{ _metronome_debug_symbols_package_name }}"
    state: present
  when: metronome_install_debug_symbols_package
  tags:
    - install

- include: configure.yml

- name: Start and enable the Metronome service
  service:
    name: metronome
    state: started
    enabled: true
  tags:
    - service
