---

###
# Metronome Repository
###

- include: "repo-{{ ansible_os_family }}.yml"
  when: metronome_configure_repo
  tags:
    - install
    - repository

###
# Metronome Setup
###

- name: Install metronome
  package:
    name: metronome
    state: present
  tags:
    - install

- include: configure.yml

- name: Start and enable the Metronome service
  service:
    name: metronome
    state: started
    enabled: true
  tags:
    - service
