- name: Add override directory for metronome.service
  file:
    name: /etc/systemd/systemd/metronome.service.d
    state: directory
  when: ansible_service_mgr == "systemd"

- name: Add unit-file with custom settings
  template:
    src: metronome.service.j2
    dest: /etc/systemd/system/metronome.service.d/override.conf
  notify:
   - systemctl daemon-reload (metronome)
   - restart metronome
  when: ansible_service_mgr == "systemd"

- name: Add defaults-file with settings
  template:
    src: metronome.default.j2
    dest: /etc/default/metronome
  when: ansible_service_mgr != "systemd"
  notify:
   - restart metronome
