---

- name: Install gnupg
  package:
    name: gnupg
    state: present

- name: Import the Metronome APT repository key
  apt_key:
    url: "{{ metronome_install_repo['gpg_key'] }}"
    id: "{{ metronome_install_repo['gpg_key_id'] | default('') }}"
    state: present
  register: _metronome_apt_key
  when: "'gpg_key' in metronome_install_repo and metronome_install_repo['gpg_key'] != ''"

- name: Add the metronome APT repository
  apt_repository:
    filename: "{{ metronome_install_repo['name'] }}"
    repo: "{{ metronome_install_repo['apt_repo'] }}"
    state: present
  register: _metronome_apt_repo

- name: Update the APT cache
  apt:
    update_cache: yes
  when: "_metronome_apt_key.changed or _metronome_apt_repo.changed"
