---

- name: Import the metronome APT repository key
  apt_key:
    url: "{{ metronome_install_repo['gpg_key'] }}"
    id: "{{ metronome_install_repo['gpg_key_id'] | default('') }}"
    state: present
  when: "'gpg_key' in metronome_install_repo and metronome_install_repo['gpg_key'] != ''"

- name: Add the metronome APT repository
  apt_repository:
    repo: "{{ metronome_install_repo['apt_repo'] }}"
    state: present

