---

- name: Install yum-plugin-priorities
  package:
    name: yum-plugin-priorities
    state: present

- name: Add the metronome YUM repository
  yum_repository:
    name: "{{ metronome_install_repo['yum_repo_name'] }}"
    description: PowerDNS Metronome Repository
    baseurl: "{{ metronome_install_repo['yum_repo_baseurl'] }}"
    gpgkey: "{{ metronome_install_repo['gpg_key'] }}"
    gpgcheck: "{{ metronome_install_repo['gpg_key'] != '' }}"
    priority: 90
    state: present
